### ISSUE TITLE
don't repeat yourself even more

### ISSUE THREAD

**Issue by StoneCypher** [Ehawk82/Ehawk82-TicTacToe#10]
lol i swear that's a sentence

so, great job on the DRY patch.  that's much less code, and much easier to debug

but i think we can do *even better*

```javascript
	r1x: function(tds){ return tds[0].innerHTML === "X" && tds[1].innerHTML === "X" && tds[2].innerHTML === "X" },
	r2x: function(tds){ return tds[3].innerHTML === "X" && tds[4].innerHTML === "X" && tds[5].innerHTML === "X" },
	r3x: function(tds){ return tds[6].innerHTML === "X" && tds[7].innerHTML === "X" && tds[8].innerHTML === "X" },
```

This is, basically, the same thing three times.

What if I wanted this instead?

```javascript
        test: /* ... this is you ... */ ,
	r1x: function(tds) { test(tds, 0, 1, 2, "X") },
	r2x: function(tds) { test(tds, 3, 4, 5, "X") },
	r3x: function(tds) { test(tds, 6, 7, 8, "X") },
```

**Comment by StoneCypher** [comment]
also, you know, once this is done, follow through on the remaining common sense part please

i'll trust you to figure out what that is

**Comment by Ehawk82** [comment]
Hello again Mr StoneCypher, though I spent three days trying to ascertain the meaning of "the common sense part", I have failed to figure out what that means in relation to meeting threshold.  Please advise; I may need some education on the matter.

Things I have brainstormed(not in order of chronological epiphany): 
- Sounds
- More buttons for things like settings, credits, and leader board.
- Getting a dollar VPS or Amazon VPC to host a site that showcases git pages via anchor tags.
- Colors?
- I still hate my font choice.  It's not consistent on all my devices.
- Responsive CSS for landscape vs portrait query.
- Instead of sending the whole thing to append to "body"; detect first, then point the code to a designated obfuscated className, then append the program to that element.
- Meta changes to name, description, and author(use my individual proprietor name instead of my real name?)
- Fixed position footer tag to hold links to various data such as license, policy, git contact info, etc.
- Issue closure.  I have no idea what i'm doing and this part has an expected learning curve.
- Donation button, and/or link to source code.
- Share the page publicly to the indie game FB group for an objective critique and important feedback
- Documentation and comments:  I should help other collaborators be able to read my code?

I probably over-thought AND under-thought in this task. Forgive me.

**Comment by StoneCypher** [comment]
no dude you're way overthinking it

just go implement `test`
